version: "3.3"

services:
  loki:
    user: root
    image: grafana/loki:3.0.0
    ports:
      - 3100:3100
    volumes:
      - ./data/loki:/loki
      - ./config/loki:/etc/loki
    container_name: loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - grafana_network

  promtail:
    user: root
    image: grafana/promtail:3.0.0
    volumes:
      - ./config/promtail:/etc/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-docker-config.yaml
    networks:
      - grafana_network

  grafana:
    user: root
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./data/dashboard:/var/lib/grafana
    ports:
      - 5000:5000
    environment:
      - GF_SERVER_HTTP_PORT=5000
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - grafana_network
    depends_on:
      - loki

networks:
  grafana_network:
    external: true

volumes:
  src:
    driver: local
